export const lineUpData = {
  1: { // Premier League: Nottingham Forest vs Manchester United
    home: {
      team: 'Nottingham Forest',
      formation: '3-4-1-2',
      starters: [
        { number: 13, name: 'W. Hennessey', position: 'GK', x: 50, y: 95 },
        { number: 5, name: 'O. Mangala', position: 'DF', x: 20, y: 80 },
        { number: 26, name: 'McKenna', position: 'DF', x: 50, y: 80 },
        { number: 19, name: 'Niakhate', position: 'DF', x: 80, y: 80 },
        { number: 7, name: 'N. Williams', position: 'MF', x: 10, y: 60 },
        { number: 23, name: 'Freuler', position: 'MF', x: 35, y: 60 },
        { number: 28, name: 'Danilo', position: 'MF', x: 65, y: 60 },
        { number: 3, name: 'R. Lodi', position: 'MF', x: 90, y: 60 },
        { number: 10, name: 'Gibbs-White', position: 'AM', x: 50, y: 40 },
        { number: 20, name: 'B. Johnson', position: 'FW', x: 35, y: 20 },
        { number: 9, name: 'T. Awoniyi', position: 'FW', x: 65, y: 20 },
      ],
      substitutes: [
        { number: 13, name: 'W. Hennessey', position: 'GK' },
        { number: 5, name: 'O. Mangala', position: 'DF' },
        { number: 11, name: 'J. Lingard', position: 'MF' },
        { number: 20, name: 'S. Surridge', position: 'FW' },
        { number: 25, name: 'E. Dennis', position: 'FW' },
        { number: 4, name: 'J. Worrall', position: 'DF' },
        { number: 8, name: 'J. Shelvey', position: 'MF' },
        { number: 15, name: 'H. Toffolo', position: 'DF' },
        { number: 34, name: 'A. Ayew', position: 'FW' },
      ],
      manager: 'S. Cooper',
      missedPlayers: [
        { name: 'S. Aurier', reason: 'Knock' },
        { name: 'D. Henderson (GK)', reason: 'Thigh Injury' },
        { name: 'C. Wood', reason: 'Thigh Injury' },
        { name: 'C. Kouyate', reason: 'Thigh Injury' },
      ],
    },
    away: {
      team: 'Manchester United',
      formation: '4-3-3',
      starters: [
        { number: 1, name: 'D. De Gea', position: 'GK', x: 50, y: 5 },
        { number: 20, name: 'D. Dalot', position: 'DF', x: 10, y: 20 },
        { number: 5, name: 'H. Maguire', position: 'DF', x: 35, y: 20 },
        { number: 2, name: 'V. Lindelof', position: 'DF', x: 65, y: 20 },
        { number: 29, name: 'Wan Bissaka', position: 'DF', x: 90, y: 20 },
        { number: 18, name: 'Casemiro', position: 'MF', x: 35, y: 40 },
        { number: 14, name: 'C. Eriksen', position: 'MF', x: 65, y: 40 },
        { number: 25, name: 'J. Sancho', position: 'FW', x: 10, y: 60 },
        { number: 8, name: 'B. Fernandes', position: 'FW', x: 50, y: 60 },
        { number: 21, name: 'Antony', position: 'FW', x: 90, y: 60 },
        { number: 9, name: 'A. Martial', position: 'FW', x: 50, y: 80 },
      ],
      substitutes: [
        { number: 31, name: 'J. Butland', position: 'GK' },
        { number: 30, name: 'N. Bishop', position: 'GK' },
        { number: 17, name: 'Fred', position: 'MF' },
        { number: 27, name: 'W. Weghorst', position: 'FW' },
        { number: 28, name: 'F. Pellistri', position: 'FW' },
        { number: 33, name: 'B. Williams', position: 'DF' },
        { number: 36, name: 'A. Elanga', position: 'FW' },
        { number: 55, name: 'Z. Iqbal', position: 'MF' },
        { number: 63, name: 'M. Jurado', position: 'DF' },
      ],
      manager: 'E. ten Hag',
      missedPlayers: [
        { name: 'A. Garnacho', reason: 'Foot Injury' },
        { name: 'M. Rashford', reason: 'Muscle Injury' },
        { name: 'L. Shaw', reason: 'Thigh Injury' },
        { name: 'R. Varane', reason: 'Muscle Injury' },
      ],
    },
  },
  2: { // La Liga: Real Madrid vs Barcelona
    home: {
      team: 'Real Madrid',
      formation: '4-3-3',
      starters: [
        { number: 1, name: 'Courtois', position: 'GK', x: 50, y: 95 },
        { number: 2, name: 'Carvajal', position: 'DF', x: 10, y: 80 },
        { number: 4, name: 'Alaba', position: 'DF', x: 35, y: 80 },
        { number: 22, name: 'Rüdiger', position: 'DF', x: 65, y: 80 },
        { number: 23, name: 'Mendy', position: 'DF', x: 90, y: 80 },
        { number: 8, name: 'Kroos', position: 'MF', x: 35, y: 60 },
        { number: 10, name: 'Modrić', position: 'MF', x: 65, y: 60 },
        { number: 15, name: 'Valverde', position: 'MF', x: 50, y: 40 },
        { number: 20, name: 'Vinícius Jr.', position: 'FW', x: 10, y: 20 },
        { number: 9, name: 'Benzema', position: 'FW', x: 50, y: 20 },
        { number: 21, name: 'Rodrygo', position: 'FW', x: 90, y: 20 },
      ],
      substitutes: [
        { number: 13, name: 'Lunin', position: 'GK' },
        { number: 6, name: 'Nacho', position: 'DF' },
        { number: 11, name: 'Asensio', position: 'FW' },
        { number: 17, name: 'Lucas Vázquez', position: 'DF' },
        { number: 24, name: 'Ceballos', position: 'MF' },
      ],
      manager: 'Carlo Ancelotti',
      missedPlayers: [
        { name: 'E. Militão', reason: 'Knee Injury' },
        { name: 'A. Tchouaméni', reason: 'Muscle Injury' },
      ],
    },
    away: {
      team: 'Barcelona',
      formation: '4-3-3',
      starters: [
        { number: 1, name: 'Ter Stegen', position: 'GK', x: 50, y: 5 },
        { number: 2, name: 'Sergi Roberto', position: 'DF', x: 10, y: 20 },
        { number: 4, name: 'Araujo', position: 'DF', x: 35, y: 20 },
        { number: 15, name: 'Christensen', position: 'DF', x: 65, y: 20 },
        { number: 18, name: 'Balde', position: 'DF', x: 90, y: 20 },
        { number: 5, name: 'Busquets', position: 'MF', x: 35, y: 40 },
        { number: 8, name: 'Pedri', position: 'MF', x: 65, y: 40 },
        { number: 21, name: 'De Jong', position: 'MF', x: 50, y: 60 },
        { number: 7, name: 'Ferran Torres', position: 'FW', x: 10, y: 80 },
        { number: 9, name: 'Lewandowski', position: 'FW', x: 50, y: 80 },
        { number: 11, name: 'Raphinha', position: 'FW', x: 90, y: 80 },
      ],
      substitutes: [
        { number: 13, name: 'Iñaki Peña', position: 'GK' },
        { number: 17, name: 'Kessié', position: 'MF' },
        { number: 19, name: 'Koundé', position: 'DF' },
        { number: 22, name: 'Ansu Fati', position: 'FW' },
        { number: 23, name: 'Eric García', position: 'DF' },
      ],
      manager: 'Xavi',
      missedPlayers: [
        { name: 'O. Dembélé', reason: 'Hamstring Injury' },
        { name: 'A. Christensen', reason: 'Muscle Injury' },
      ],
    },
  },
  3: { // Serie A: AC Milan vs Inter Milan
    home: {
      team: 'AC Milan',
      formation: '4-2-3-1',
      starters: [
        { number: 16, name: 'Maignan', position: 'GK', x: 50, y: 95 },
        { number: 2, name: 'Calabria', position: 'DF', x: 10, y: 80 },
        { number: 23, name: 'Tomori', position: 'DF', x: 35, y: 80 },
        { number: 24, name: 'Kjær', position: 'DF', x: 65, y: 80 },
        { number: 19, name: 'Hernández', position: 'DF', x: 90, y: 80 },
        { number: 8, name: 'Tonali', position: 'MF', x: 35, y: 60 },
        { number: 4, name: 'Bennacer', position: 'MF', x: 65, y: 60 },
        { number: 17, name: 'Leão', position: 'AM', x: 10, y: 40 },
        { number: 10, name: 'Díaz', position: 'AM', x: 50, y: 40 },
        { number: 11, name: 'Saelemaekers', position: 'AM', x: 90, y: 40 },
        { number: 9, name: 'Giroud', position: 'FW', x: 50, y: 20 },
      ],
      substitutes: [
        { number: 1, name: 'Tătărușanu', position: 'GK' },
        { number: 5, name: 'Ballo-Touré', position: 'DF' },
        { number: 7, name: 'Rebic', position: 'FW' },
        { number: 12, name: 'Pobega', position: 'MF' },
        { number: 20, name: 'Kalulu', position: 'DF' },
      ],
      manager: 'S. Pioli',
      missedPlayers: [
        { name: 'Z. Ibrahimović', reason: 'Knee Injury' },
        { name: 'A. Florenzi', reason: 'Muscle Injury' },
      ],
    },
    away: {
      team: 'Inter Milan',
      formation: '3-5-2',
      starters: [
        { number: 24, name: 'Onana', position: 'GK', x: 50, y: 5 },
        { number: 37, name: 'Skriniar', position: 'DF', x: 10, y: 20 },
        { number: 6, name: 'De Vrij', position: 'DF', x: 35, y: 20 },
        { number: 95, name: 'Bastoni', position: 'DF', x: 65, y: 20 },
        { number: 2, name: 'Dumfries', position: 'MF', x: 10, y: 40 },
        { number: 23, name: 'Barella', position: 'MF', x: 35, y: 40 },
        { number: 20, name: 'Çalhanoğlu', position: 'MF', x: 50, y: 40 },
        { number: 22, name: 'Mkhitaryan', position: 'MF', x: 65, y: 40 },
        { number: 32, name: 'Dimarco', position: 'MF', x: 90, y: 40 },
        { number: 10, name: 'Lautaro Martínez', position: 'FW', x: 35, y: 60 },
        { number: 9, name: 'Džeko', position: 'FW', x: 65, y: 60 },
      ],
      substitutes: [
        { number: 1, name: 'Handanović', position: 'GK' },
        { number: 5, name: 'Gagliardini', position: 'MF' },
        { number: 11, name: 'Correa', position: 'FW' },
        { number: 14, name: 'Asllani', position: 'MF' },
        { number: 21, name: 'Acerbi', position: 'DF' },
      ],
      manager: 'S. Inzaghi',
      missedPlayers: [
        { name: 'R. Lukaku', reason: 'Muscle Injury' },
        { name: 'M. Brozović', reason: 'Calf Injury' },
      ],
    },
  },
};